### ISSUE TITLE
Cannot pipe passwords to `tpm insert`

### ISSUE THREAD

**Issue by aecepoglu** [thexhr/tpm#2]
I cannot pipe passwords to `tpm insert`.

The following should insert a password: `echo hello | tpm insert testing` but it doesn't.

**Comment by thexhr** [comment]
Yes, that's actually a feature and not a bug. If you pipe a password in tpm it will be visible in the process listing of the system. Even if it's there only for a short time it could be visible to another untrusted user on the system or worse, end up in a monitoring/audit solution that logs process creations.

**Comment by aecepoglu** [comment]
But `pwgen -1 | tpm insert website.com/myusername` is a tpm use case, as can be seen here: https://github.com/nmeum/tpm#examples .

If you disabled that on purpose though, I understand; but it seems like `readpw()` method still has logic for reading from stdin.

**Comment by aecepoglu** [comment]
Have you missed my reply maybe?

**Comment by thexhr** [comment]
Actually I missed your reply. Sorry for that.

However, the described behavior actually works without your change.

```
$ echo test | ./tpm insert test/test
$ ./tpm test/test
test
```

Can you please confirm that it's working for you? Without your patch

**Comment by aecepoglu** [comment]
It does seem to work. I remember it didn't use to so I'm not sure if I wasn't testing it fine or if it got fixed.
